services:
  # ----------------------------------------------------
  # Express Backend Web Service
  # ----------------------------------------------------
  - type: web
    name: car-recommendation-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://car_dekho:ktSMNBQmzvEBcYKef53A5QABvyRNP5g0@dpg-d8dj7828qa3s739p0460-a.singapore-postgres.render.com/car_dekho
      - key: GROQ_API_KEY
        value: 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
      - key: GROQ_MODEL
        value: openai/gpt-oss-120b
      - key: FRONTEND_URL
        value: https://car-recommendation-frontend-2mdk.onrender.com

  # ----------------------------------------------------
  # React Frontend Static Site
  # ----------------------------------------------------
  - type: web
    name: car-recommendation-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://car-recommendation-backend-s9oc.onrender.com/api
