const { AppDataSource } = require('../config/data-source');

const cars = [
  // --- HATCHBACKS ---
  {
    brand: 'Maruti Suzuki', model: 'Swift', variant: 'ZXi+ AGS', year: 2024,
    price_ex_showroom: 894000, price_on_road: 1035000, body_type: 'hatchback',
    fuel_type: 'petrol', transmission: 'amt', engine_displacement: 1197,
    max_power: '89 bhp @ 6000 rpm', max_torque: '113 Nm @ 4400 rpm',
    mileage_kmpl: 24.80, seating_capacity: 5, boot_space_litres: 268,
    ground_clearance_mm: 163, safety_rating: 3,
    key_features: ['touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Pearl Arctic White', 'Sizzling Red', 'Midnight Blue', 'Magma Grey'],
    pros: ['Excellent fuel efficiency', 'Fun to drive', 'Peppy engine', 'Strong resale value'],
    cons: ['Compact rear seat', 'Basic safety features', 'No sunroof'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Hyundai', model: 'i20', variant: 'Asta (O) 1.0 Turbo DCT', year: 2024,
    price_ex_showroom: 1165000, price_on_road: 1340000, body_type: 'hatchback',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 998,
    max_power: '118 bhp @ 6000 rpm', max_torque: '172 Nm @ 1500-4000 rpm',
    mileage_kmpl: 20.25, seating_capacity: 5, boot_space_litres: 311,
    ground_clearance_mm: 170, safety_rating: 3,
    key_features: ['sunroof', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'alloy_wheels', 'air_purifier'],
    colors_available: ['Polar White', 'Fiery Red', 'Starry Night', 'Titan Grey', 'Lucid Lime'],
    pros: ['Feature-loaded', 'Powerful turbo engine', 'Premium interiors', 'Smooth DCT'],
    cons: ['Stiff ride quality', 'Expensive top variant', 'Turbo lag at low speeds'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Tata', model: 'Altroz', variant: 'XZ+ Dark Edition', year: 2024,
    price_ex_showroom: 985000, price_on_road: 1125000, body_type: 'hatchback',
    fuel_type: 'petrol', transmission: 'manual', engine_displacement: 1199,
    max_power: '86 bhp @ 6000 rpm', max_torque: '113 Nm @ 3300 rpm',
    mileage_kmpl: 22.07, seating_capacity: 5, boot_space_litres: 345,
    ground_clearance_mm: 165, safety_rating: 5,
    key_features: ['touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Harbour Blue', 'Opera Blue', 'High Street Gold', 'Avenue White'],
    pros: ['5-star safety rating', 'Spacious cabin', 'Good build quality', 'Premium feel'],
    cons: ['Engine feels underpowered', 'No automatic option', 'Missing ventilated seats'],
    image_url: null, is_available: true,
  },

  // --- SEDANS ---
  {
    brand: 'Hyundai', model: 'Verna', variant: 'SX (O) 1.5 Turbo DCT', year: 2024,
    price_ex_showroom: 1750000, price_on_road: 1990000, body_type: 'sedan',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 1482,
    max_power: '158 bhp @ 5500 rpm', max_torque: '253 Nm @ 1500-3500 rpm',
    mileage_kmpl: 20.60, seating_capacity: 5, boot_space_litres: 480,
    ground_clearance_mm: 165, safety_rating: 5,
    key_features: ['sunroof', 'adas', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Abyss Black', 'Fiery Red', 'Tellurian Brown', 'Titan Grey'],
    pros: ['Powerful turbo engine', 'Feature-rich', 'ADAS suite', '5-star safety'],
    cons: ['Expensive', 'Firm rear seat', 'DCT hesitation in traffic'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Honda', model: 'City', variant: 'ZX CVT', year: 2024,
    price_ex_showroom: 1515000, price_on_road: 1720000, body_type: 'sedan',
    fuel_type: 'petrol', transmission: 'cvt', engine_displacement: 1498,
    max_power: '119 bhp @ 6600 rpm', max_torque: '145 Nm @ 4300 rpm',
    mileage_kmpl: 18.40, seating_capacity: 5, boot_space_litres: 506,
    ground_clearance_mm: 165, safety_rating: 4,
    key_features: ['sunroof', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'cruise_control'],
    colors_available: ['Platinum White Pearl', 'Radiant Red', 'Lunar Silver', 'Golden Brown'],
    pros: ['Reliable Honda engine', 'Spacious cabin', 'Excellent ride quality', 'Big boot'],
    cons: ['Less powerful than rivals', 'Missing ADAS', 'CVT feels sluggish'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Maruti Suzuki', model: 'Ciaz', variant: 'Alpha AT', year: 2024,
    price_ex_showroom: 1200000, price_on_road: 1370000, body_type: 'sedan',
    fuel_type: 'petrol', transmission: 'automatic', engine_displacement: 1462,
    max_power: '103 bhp @ 6000 rpm', max_torque: '138 Nm @ 4400 rpm',
    mileage_kmpl: 20.04, seating_capacity: 5, boot_space_litres: 510,
    ground_clearance_mm: 170, safety_rating: 3,
    key_features: ['touchscreen', 'android_auto', 'rear_camera', 'auto_headlights', 'cruise_control', 'push_start'],
    colors_available: ['Pearl Arctic White', 'Nexa Blue', 'Grandeur Grey', 'Celestial Blue'],
    pros: ['Great mileage', 'Spacious rear seat', 'Smooth AT', 'Affordable sedan'],
    cons: ['Dated design', 'Missing sunroof', 'Average safety rating'],
    image_url: null, is_available: true,
  },

  // --- COMPACT SUVs ---
  {
    brand: 'Tata', model: 'Nexon', variant: 'Creative+ S DCA', year: 2024,
    price_ex_showroom: 1525000, price_on_road: 1750000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 1199,
    max_power: '118 bhp @ 5500 rpm', max_torque: '170 Nm @ 1750-4000 rpm',
    mileage_kmpl: 17.80, seating_capacity: 5, boot_space_litres: 382,
    ground_clearance_mm: 209, safety_rating: 5,
    key_features: ['sunroof', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'air_purifier'],
    colors_available: ['Creative Ocean', 'Fearless Purple', 'Daytona Grey', 'Pure White'],
    pros: ['5-star safety', 'Feature-loaded', 'High ground clearance', 'Turbo engine'],
    cons: ['Cramped rear seat', 'Average boot space', 'Turbo lag'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Hyundai', model: 'Venue', variant: 'SX (O) 1.0 Turbo DCT', year: 2024,
    price_ex_showroom: 1340000, price_on_road: 1530000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 998,
    max_power: '118 bhp @ 6000 rpm', max_torque: '172 Nm @ 1500-4000 rpm',
    mileage_kmpl: 18.10, seating_capacity: 5, boot_space_litres: 381,
    ground_clearance_mm: 195, safety_rating: 3,
    key_features: ['sunroof', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Phantom Black', 'Fiery Red', 'Denim Blue', 'Typhoon Silver'],
    pros: ['Compact city SUV', 'Turbo engine', 'Feature-loaded', 'Good DCT'],
    cons: ['Tight rear seat', 'Average safety rating', 'Stiff ride'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Kia', model: 'Sonet', variant: 'HTX+ 1.0 Turbo DCT', year: 2024,
    price_ex_showroom: 1385000, price_on_road: 1580000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 998,
    max_power: '118 bhp @ 6000 rpm', max_torque: '172 Nm @ 1500-4000 rpm',
    mileage_kmpl: 18.20, seating_capacity: 5, boot_space_litres: 392,
    ground_clearance_mm: 205, safety_rating: 3,
    key_features: ['sunroof', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Intense Red', 'Aurora Black Pearl', 'Glacier White Pearl', 'Gravity Grey'],
    pros: ['Sporty design', 'Ventilated seats', 'Good tech package', 'Fun to drive'],
    cons: ['Compact rear seat', 'DCT jerkiness in traffic', 'Average safety'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Maruti Suzuki', model: 'Brezza', variant: 'ZXi+ AT', year: 2024,
    price_ex_showroom: 1390000, price_on_road: 1570000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'automatic', engine_displacement: 1462,
    max_power: '103 bhp @ 6000 rpm', max_torque: '137 Nm @ 4400 rpm',
    mileage_kmpl: 19.80, seating_capacity: 5, boot_space_litres: 328,
    ground_clearance_mm: 198, safety_rating: 4,
    key_features: ['sunroof', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'cruise_control'],
    colors_available: ['Pearl Arctic White', 'Brave Khaki', 'Sizzling Red', 'Exquisite Blue'],
    pros: ['Excellent mileage', 'Reliable engine', 'Good resale', 'Spacious cabin'],
    cons: ['Underwhelming power', 'Basic AT gearbox', 'Average ride quality'],
    image_url: null, is_available: true,
  },

  // --- MID-SIZE SUVs ---
  {
    brand: 'Hyundai', model: 'Creta', variant: 'SX (O) 1.5 Turbo DCT', year: 2024,
    price_ex_showroom: 2010000, price_on_road: 2280000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 1482,
    max_power: '158 bhp @ 5500 rpm', max_torque: '253 Nm @ 1500-3500 rpm',
    mileage_kmpl: 18.40, seating_capacity: 5, boot_space_litres: 433,
    ground_clearance_mm: 190, safety_rating: 5,
    key_features: ['sunroof', 'adas', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Atlas White', 'Abyss Black', 'Fiery Red', 'Titan Grey', 'Ranger Khaki'],
    pros: ['Feature-loaded', 'ADAS suite', 'Powerful turbo', '5-star safety', 'Spacious cabin'],
    cons: ['Expensive top variant', 'Average rear legroom', 'Turbo-only DCT'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Kia', model: 'Seltos', variant: 'HTX+ 1.5 Turbo DCT', year: 2024,
    price_ex_showroom: 1920000, price_on_road: 2170000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 1482,
    max_power: '158 bhp @ 5500 rpm', max_torque: '253 Nm @ 1500-3500 rpm',
    mileage_kmpl: 18.00, seating_capacity: 5, boot_space_litres: 433,
    ground_clearance_mm: 190, safety_rating: 5,
    key_features: ['sunroof', 'adas', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Intense Red', 'Aurora Black Pearl', 'Glacier White Pearl', 'Imperial Blue'],
    pros: ['ADAS safety', 'Powerful turbo', 'Premium interiors', 'Great value'],
    cons: ['DCT can be jerky', 'Road noise at speed', 'Touch-heavy controls'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Tata', model: 'Harrier', variant: 'Fearless+ AT', year: 2024,
    price_ex_showroom: 2510000, price_on_road: 2830000, body_type: 'suv',
    fuel_type: 'diesel', transmission: 'automatic', engine_displacement: 1956,
    max_power: '168 bhp @ 3750 rpm', max_torque: '350 Nm @ 1750-2500 rpm',
    mileage_kmpl: 16.80, seating_capacity: 5, boot_space_litres: 425,
    ground_clearance_mm: 198, safety_rating: 5,
    key_features: ['sunroof', 'adas', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'air_purifier'],
    colors_available: ['Coral Red', 'Oberon Black', 'Lunar White', 'Ash Grey'],
    pros: ['Road presence', '5-star safety', 'Powerful diesel', 'ADAS', 'JBL audio'],
    cons: ['Diesel only', 'Heavy in city', 'Average fuel economy'],
    image_url: null, is_available: true,
  },
  {
    brand: 'MG', model: 'Hector', variant: 'Sharp Pro CVT', year: 2024,
    price_ex_showroom: 2100000, price_on_road: 2380000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'cvt', engine_displacement: 1451,
    max_power: '141 bhp @ 5000 rpm', max_torque: '250 Nm @ 1600-3600 rpm',
    mileage_kmpl: 15.80, seating_capacity: 5, boot_space_litres: 587,
    ground_clearance_mm: 192, safety_rating: 4,
    key_features: ['sunroof', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'cruise_control', 'ventilated_seats'],
    colors_available: ['Candy White', 'Glaze Red', 'Aurora Silver', 'Starry Black'],
    pros: ['14-inch touchscreen', 'Massive boot', 'Connected car features', 'Value for money'],
    cons: ['CVT feels sluggish', 'Average build quality', 'Heavy car'],
    image_url: null, is_available: true,
  },

  // --- PREMIUM / FULL-SIZE SUVs ---
  {
    brand: 'Mahindra', model: 'XUV700', variant: 'AX7 L AT', year: 2024,
    price_ex_showroom: 2460000, price_on_road: 2780000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'automatic', engine_displacement: 1997,
    max_power: '197 bhp @ 5000 rpm', max_torque: '380 Nm @ 1750-3000 rpm',
    mileage_kmpl: 13.20, seating_capacity: 7, boot_space_litres: 451,
    ground_clearance_mm: 200, safety_rating: 5,
    key_features: ['sunroof', 'adas', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'ventilated_seats', 'cruise_control'],
    colors_available: ['Everest White', 'Midnight Black', 'Dazzle Silver', 'Red Rage', 'Electric Blue'],
    pros: ['Powerful engine', 'ADAS suite', '7-seater', '5-star safety', 'Dual screens'],
    cons: ['Long waiting period', 'Average third-row space', 'Fuel economy'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Mahindra', model: 'XUV700', variant: 'AX7 L Diesel AT', year: 2024,
    price_ex_showroom: 2690000, price_on_road: 3040000, body_type: 'suv',
    fuel_type: 'diesel', transmission: 'automatic', engine_displacement: 2184,
    max_power: '182 bhp @ 3500 rpm', max_torque: '420 Nm @ 1600-2800 rpm',
    mileage_kmpl: 16.40, seating_capacity: 7, boot_space_litres: 451,
    ground_clearance_mm: 200, safety_rating: 5,
    key_features: ['sunroof', 'adas', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'ventilated_seats', 'cruise_control'],
    colors_available: ['Everest White', 'Midnight Black', 'Dazzle Silver', 'Red Rage'],
    pros: ['Torquey diesel', 'ADAS', '7-seater', '5-star safety', 'Best-in-class features'],
    cons: ['Long waiting period', 'Heavy car', 'Third row is tight'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Tata', model: 'Safari', variant: 'Accomplished+ AT', year: 2024,
    price_ex_showroom: 2670000, price_on_road: 3010000, body_type: 'suv',
    fuel_type: 'diesel', transmission: 'automatic', engine_displacement: 1956,
    max_power: '168 bhp @ 3750 rpm', max_torque: '350 Nm @ 1750-2500 rpm',
    mileage_kmpl: 14.50, seating_capacity: 7, boot_space_litres: 380,
    ground_clearance_mm: 198, safety_rating: 5,
    key_features: ['sunroof', 'adas', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'air_purifier'],
    colors_available: ['Stellar Frost', 'Oberon Black', 'Cosmic Gold', 'Stardust Ash'],
    pros: ['7-seater', 'Commanding road presence', '5-star safety', 'ADAS'],
    cons: ['Diesel only', 'Third row is tight', 'Average mileage'],
    image_url: null, is_available: true,
  },

  // --- MUVs ---
  {
    brand: 'Maruti Suzuki', model: 'Ertiga', variant: 'ZXi+ AT', year: 2024,
    price_ex_showroom: 1310000, price_on_road: 1490000, body_type: 'muv',
    fuel_type: 'petrol', transmission: 'automatic', engine_displacement: 1462,
    max_power: '103 bhp @ 6000 rpm', max_torque: '137 Nm @ 4400 rpm',
    mileage_kmpl: 20.30, seating_capacity: 7, boot_space_litres: 209,
    ground_clearance_mm: 185, safety_rating: 3,
    key_features: ['touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'cruise_control'],
    colors_available: ['Pearl Arctic White', 'Midnight Black', 'Magma Grey', 'Oxford Blue'],
    pros: ['Best-in-class mileage', 'Affordable 7-seater', 'Reliable engine', 'Easy to drive'],
    cons: ['Underwhelming power', 'Basic safety', 'Average ride quality'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Kia', model: 'Carens', variant: 'Luxury Plus 1.5 Turbo DCT', year: 2024,
    price_ex_showroom: 1790000, price_on_road: 2030000, body_type: 'muv',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 1482,
    max_power: '158 bhp @ 5500 rpm', max_torque: '253 Nm @ 1500-3500 rpm',
    mileage_kmpl: 17.70, seating_capacity: 7, boot_space_litres: 216,
    ground_clearance_mm: 195, safety_rating: 3,
    key_features: ['sunroof', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Imperial Blue', 'Intense Red', 'Glacier White Pearl', 'Aurora Black Pearl'],
    pros: ['Powerful turbo', 'Premium features', 'Spacious 3-row', 'Ventilated seats'],
    cons: ['Average third-row space', 'Boot space compromised', 'DCT in traffic'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Toyota', model: 'Innova Hycross', variant: 'VX HEV', year: 2024,
    price_ex_showroom: 2560000, price_on_road: 2890000, body_type: 'muv',
    fuel_type: 'hybrid', transmission: 'cvt', engine_displacement: 1987,
    max_power: '186 bhp (combined)', max_torque: '188 Nm', mileage_kmpl: 21.10,
    seating_capacity: 7, boot_space_litres: 240, ground_clearance_mm: 185,
    safety_rating: 5,
    key_features: ['sunroof', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'cruise_control', 'ventilated_seats'],
    colors_available: ['Super White', 'Attitude Black', 'Sparkling Black', 'Platinum White Pearl'],
    pros: ['Hybrid efficiency', 'Toyota reliability', 'Spacious cabin', '5-star safety', 'Captain seats'],
    cons: ['Expensive', 'No diesel option', 'Average boot space'],
    image_url: null, is_available: true,
  },

  // --- ELECTRIC ---
  {
    brand: 'Tata', model: 'Nexon EV', variant: 'Empowered+ LR', year: 2024,
    price_ex_showroom: 1910000, price_on_road: 2050000, body_type: 'suv',
    fuel_type: 'electric', transmission: 'automatic', engine_displacement: null,
    max_power: '141 bhp', max_torque: '215 Nm', mileage_kmpl: null,
    seating_capacity: 5, boot_space_litres: 350, ground_clearance_mm: 209,
    safety_rating: 5,
    key_features: ['sunroof', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'ventilated_seats', 'air_purifier'],
    colors_available: ['Pristine White', 'Intensi-Teal', 'Fearless Purple', 'Creative Ocean'],
    pros: ['Zero emissions', '5-star safety', 'Low running cost', '465 km range', 'Fast charging'],
    cons: ['Charging infra still growing', 'Higher upfront cost', 'Range anxiety'],
    image_url: null, is_available: true,
  },
  {
    brand: 'MG', model: 'ZS EV', variant: 'Exclusive Pro', year: 2024,
    price_ex_showroom: 2340000, price_on_road: 2490000, body_type: 'suv',
    fuel_type: 'electric', transmission: 'automatic', engine_displacement: null,
    max_power: '174 bhp', max_torque: '280 Nm', mileage_kmpl: null,
    seating_capacity: 5, boot_space_litres: 448, ground_clearance_mm: 177,
    safety_rating: 4,
    key_features: ['sunroof', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'adas'],
    colors_available: ['Ivory White', 'Aurora Silver', 'Black Pearl'],
    pros: ['461 km range', 'ADAS features', 'Spacious cabin', 'Connected car tech'],
    cons: ['Premium pricing', 'Average build quality', 'Slow charging standard'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Hyundai', model: 'Ioniq 5', variant: 'Long Range AWD', year: 2024,
    price_ex_showroom: 4495000, price_on_road: 4800000, body_type: 'suv',
    fuel_type: 'electric', transmission: 'automatic', engine_displacement: null,
    max_power: '321 bhp', max_torque: '605 Nm', mileage_kmpl: null,
    seating_capacity: 5, boot_space_litres: 527, ground_clearance_mm: 160,
    safety_rating: 5,
    key_features: ['sunroof', 'adas', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', '360_camera', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels'],
    colors_available: ['Atlas White', 'Gravity Gold', 'Midnight Black', 'Mystic Olive'],
    pros: ['Ultra-fast 800V charging', 'Stunning design', 'AWD performance', 'Vehicle-to-Load (V2L)'],
    cons: ['Very expensive', 'Low ground clearance', 'CKD assembly'],
    image_url: null, is_available: true,
  },

  // --- CNG ---
  {
    brand: 'Maruti Suzuki', model: 'Grand Vitara', variant: 'Alpha+ CNG', year: 2024,
    price_ex_showroom: 1365000, price_on_road: 1550000, body_type: 'suv',
    fuel_type: 'cng', transmission: 'manual', engine_displacement: 1462,
    max_power: '87 bhp @ 6000 rpm', max_torque: '121.5 Nm @ 4400 rpm',
    mileage_kmpl: 26.90, seating_capacity: 5, boot_space_litres: 270,
    ground_clearance_mm: 190, safety_rating: 4,
    key_features: ['touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'cruise_control'],
    colors_available: ['Arctic White', 'Grandeur Grey', 'Celestial Blue', 'Chestnut Brown'],
    pros: ['Amazing CNG mileage', 'SUV body', 'Factory-fitted CNG', 'Reliable'],
    cons: ['Reduced boot space', 'Manual only CNG', 'Power drop on CNG'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Hyundai', model: 'Exter', variant: 'SX (O) Connect CNG', year: 2024,
    price_ex_showroom: 905000, price_on_road: 1040000, body_type: 'suv',
    fuel_type: 'cng', transmission: 'manual', engine_displacement: 1197,
    max_power: '69 bhp @ 6000 rpm', max_torque: '95.2 Nm @ 4000 rpm',
    mileage_kmpl: 27.10, seating_capacity: 5, boot_space_litres: 290,
    ground_clearance_mm: 185, safety_rating: 3,
    key_features: ['touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights'],
    colors_available: ['Cosmic Blue', 'Fiery Red', 'Ranger Khaki', 'Atlas White'],
    pros: ['Most affordable SUV', 'Great CNG mileage', 'Compact city car', 'Funky design'],
    cons: ['Underpowered on CNG', 'Basic safety', 'No alloys on CNG'],
    image_url: null, is_available: true,
  },

  // --- PREMIUM ---
  {
    brand: 'Škoda', model: 'Kushaq', variant: 'Style 1.5 TSI DSG', year: 2024,
    price_ex_showroom: 1885000, price_on_road: 2130000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 1498,
    max_power: '148 bhp @ 5000-6000 rpm', max_torque: '250 Nm @ 1600-3500 rpm',
    mileage_kmpl: 17.00, seating_capacity: 5, boot_space_litres: 385,
    ground_clearance_mm: 188, safety_rating: 5,
    key_features: ['sunroof', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'cruise_control'],
    colors_available: ['Candy White', 'Tornado Red', 'Carbon Steel', 'Honey Orange'],
    pros: ['Fun to drive', '1.5 TSI is punchy', 'European build quality', '5-star safety'],
    cons: ['After-sales service', 'DSG reliability concerns', 'Average boot space'],
    image_url: null, is_available: true,
  },
  {
    brand: 'Volkswagen', model: 'Taigun', variant: 'GT Plus 1.5 TSI DSG', year: 2024,
    price_ex_showroom: 1915000, price_on_road: 2160000, body_type: 'suv',
    fuel_type: 'petrol', transmission: 'dct', engine_displacement: 1498,
    max_power: '148 bhp @ 5000-6000 rpm', max_torque: '250 Nm @ 1600-3500 rpm',
    mileage_kmpl: 17.20, seating_capacity: 5, boot_space_litres: 385,
    ground_clearance_mm: 188, safety_rating: 5,
    key_features: ['sunroof', 'ventilated_seats', 'wireless_charging', 'touchscreen', 'android_auto', 'push_start', 'rear_camera', 'auto_headlights', 'alloy_wheels', 'cruise_control'],
    colors_available: ['Candy White', 'Wild Cherry Red', 'Curcuma Yellow', 'Carbon Steel'],
    pros: ['Solid build', 'Punchy 1.5 TSI', '5-star safety', 'Fun handling'],
    cons: ['After-sales network', 'DSG in traffic', 'Premium pricing'],
    image_url: null, is_available: true,
  },
];

async function seedCars() {
  const carRepo = AppDataSource.getRepository('Car');

  const existingCount = await carRepo.count();
  if (existingCount > 0) {
    console.log(`Cars already seeded (${existingCount} found). Skipping.`);
    return;
  }

  for (const car of cars) {
    const entity = carRepo.create(car);
    await carRepo.save(entity);
  }

  console.log(`✅ Seeded ${cars.length} cars.`);
}

module.exports = { seedCars };
